name: Android Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3  # Updated to v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Maven
      uses: actions/setup-java@v3  # Updated to v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3  # Updated to v3
      with:
        path: ~/.m2/repository
        key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: maven-${{ runner.os }}-

    - name: Build with Maven
      run: mvn -B clean install

    - name: Run unit tests
      run: mvn test

    - name: Upload build outputs
      uses: actions/upload-artifact@v3  # Updated to v3
      with:
        name: build-artifacts
        path: target/
