name: Android CI/CD Pipeline

on:
  pull_request:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 17
          - os: ubuntu-latest
            java: 22
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Use Gradle 8.10 Wrapper
      run: ./gradlew wrapper --gradle-version 8.10 --distribution-type all

    - name: Build with Gradle
      run: ./gradlew build --stacktrace --console=plain