name: Android CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v2

    # Remove old workflows (optional)
    - name: Remove old workflows
      run: rm -rf .github/workflows/*

    # Set up JDK 17 (updated from JDK 11)
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'  # or 'adopt'
        java-version: '17'

    # Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Give executable permission to gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    # Build the Android project with detailed logs
    - name: Build with Gradle (with stacktrace and info)
      run: ./gradlew build --stacktrace --info

    # Run unit tests
    - name: Run Unit Tests
      run: ./gradlew test --stacktrace --info

    # Assemble the app
    - name: Assemble Release APK
      run: ./gradlew assembleRelease --stacktrace --info

    # Archive the built APK
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: android-app
        path: app/build/outputs/apk/release/app-release.apk
