name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 35  # Use the appropriate SDK version for your project
        build-tools: 35.0.0  # Make sure this matches the build tools version you're using

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set Gradle version to 8.10
      run: ./gradlew wrapper --gradle-version 8.10

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run unit tests
      run: ./gradlew tes
